const WORKFLOW_EXECUTION_INITIALIZE_FUNCTION_ID =
  "initialize-workflow-execution";
const WORKFLOW_EXECUTION_START_FUNCTION_ID = "start-workflow-execution";

const WORKFLOW_EXECUTION_TRIGGERED_EVENT = "workflow/execution.triggered";
const WORKFLOW_EXECUTION_INITIALIZED_EVENT = "workflow/execution.initialized";

export {
  WORKFLOW_EXECUTION_INITIALIZE_FUNCTION_ID,
  WORKFLOW_EXECUTION_START_FUNCTION_ID,
  WORKFLOW_EXECUTION_TRIGGERED_EVENT,
  WORKFLOW_EXECUTION_INITIALIZED_EVENT,
};
